# Documenting R

The R language has a substantial body of documentation, much of which is contributed by various authors. If you are interested in contributing to R's documentation, your contributions are more than welcome. You may use the plain text format for making and submitting your contributions.

## Introduction

## Style Guide

### Whitespace

### Footnotes

### Capitalization

### Affirmative Tone

### Economy of Expression

### Security Consideration

### Code Examples

### Code Equivalents

### Audience

## reStructuredText Primer

### Paragraphs

### Inline markup

### Lists and Quotes

### Source Code

### Hyperlinks

### Sections

### Explicit Markup

### Directives

### Footnotes

### Comments

### Source encoding

### Gotchas

## Additional Markup Constructs

### Meta-information markup

### Module-specific markup

### Information units

### Showing code examples

### Inline markup

### Cross-linking markup

### Paragraph-level markup

### Table-of-contents markup

### Index-generating markup

### Grammar production displays

### Substitutions

## Building the documentation

### Using make / make.bat

### Using sphinx-build

## Translating

### Starting a new translation

### PEP 545 summary:

### How to get help

### Translation FAQ


# Helping with Documentation

## R Core Documentation

## Helping with Documentation

## Proofreading

## Helping with the Developer's Guide

## Developer's Guide workflow



## See also