# Where to get help {#WhereToGetHelp}

If you are working on R it is possible that you will come across an issue where you would need some assistance to solve it. If you require help, there are options available to seek assistance or get some feedback which are discussed in this chapter. If the question involves process or tool usage then please check the rest of this guide first as it should answer your question. Please make sure to search the documentation and resources to see if your question has already been addressed. If not, then ask for assistance in the appropriate forum. Many developers are volunteers and please be polite, patient, and thoughtful when requesting for feedback or help.

## Slack

You can discuss issues related to the development of R and learn about the process of contributing to R on the [R-devel slack](https://r-devel.slack.com/). There are a number of experienced developers on this slack who can answer questions and/or provide feedback. The following channels are available on the R-devel slack for help and feedback with specific areas:

  * #bugreports-for-review: Share bug reports for review/feedback before submitting to Bugzilla.
  
  * #core-dev-help: Getting help on anything related to R Core contribution.
  
  * #core-documentation: Discuss patches/improvements to R's documentation.
  
  * #core-translation: Discuss translating R messages, warnings, and errors into non-English languages.
  
  * #patches-for-review: Share patches for peer review before submitting to R Core.

Note: You may not be able to access the history of these channels, so it cannot be used as a knowledge base of sorts. 

## Mailing Lists

There are quite a few [mailing lists](https://www.r-project.org/mail.html) for getting help with R:

  * [R-devel](https://stat.ethz.ch/mailman/listinfo/r-devel): 
      * Questions and discussion about development _of_ R vs. _with_ R.
      * Getting help with technical programming issues, e.g. interfacing R with C/C++.
      * Proposals of new functionality for R.
      * Pre-testing of new versions of R.
      * Enhancements and patches to the R source code and the R documentation.
      * Posting examples and benchmarks.
      
  * [R-help](https://stat.ethz.ch/mailman/listinfo/r-help): 
      * Discussions about problems and solutions using R.
      
  * [R-package-devel](https://stat.ethz.ch/mailman/listinfo/r-package-devel): 
      * Getting help about package development in R.
      * Learning about the package development process. 
      * Discussing problems developing a package (or problem in passing the R CMD check).
      
Please avoid cross-posting to both the R-package-devel and the R-devel mailing lists.

## File a Bug

If you strongly suspect you have come across a bug (be it in the build process, or in other areas), then [report it on Bugzilla](#ReportBug). 
