# News and Announcements {#News}

Here are some resources that can be useful to keep up with the developments in R:

## Blogs

The [R project](https://www.r-project.org/) maintains a list of public [blogs](https://developer.r-project.org/Blog/public/) mainly written by the R Core Development Team. Daily news about R-devel can be found [here](https://developer.r-project.org/blosxom.cgi/R-devel).

## Conferences

Updates about conferences actively supported or endorsed by The R Foundation can be found [here](https://www.r-project.org/conferences/). These conferences are organised by members from the R community.

## Journal

[The R Journal](https://journal.r-project.org/) is an open access and refereed journal featuring short to medium length articles that should be of interest to users or developers of R. It also has a news section where information on, changes in R (new features of the latest release), changes on CRAN (new add-on packages, manuals, binary contributions, mirrors, etc.), upcoming conferences, and conference reports is provided.


## Mailing lists

  * [R-announce](https://stat.ethz.ch/mailman/listinfo/r-announce): A moderated mailing list used for announcements by the R Core Development Team. Major announcements about the development of R and the availability of new code are made here.
  * [R-packages](https://stat.ethz.ch/mailman/listinfo/r-packages): A moderated mailing list for announcements about contributed R packages (typically on [CRAN](https://cran.r-project.org/)) and similar R project extensions.

## Twitter

Follow [\@R_dev_news](https://twitter.com/R_dev_news) on Twitter for the [R development updates](https://developer.r-project.org/RSSfeeds.html) and [blog post](https://developer.r-project.org/Blog/public/) announcements.
