# Developer Tools {#sec-dev-tools}

This chapter lists resources and tools which R developers may use. Here we will go over some commonly used tools that are relevant to R’s workflow. As there are several ways to accomplish these tasks, this chapter reflects methods suitable for new contributors. Experienced contributors may desire a different approach.

## Subversion (svn) client

Subversion (svn) is a version control system that tracks any changes made to files and directories. You can install either the [TortoiseSVN](https://tortoisesvn.net/) (command line tool, and Windows Explorer integration) or the [SlikSVN](https://sliksvn.com/download/) (just the command line tool) client. They have Windows installers and can be used from Windows cmd or RStudio terminal.

Some resources for learning subversion commands:

1. [Apache Subversion quick start guide](http://subversion.apache.org/quick-start)

2. [TortoiseSVN commands](https://tortoisesvn.net/docs/nightly/TortoiseSVN_en/tsvn-cli-main.html) 

3. [SlikSVN basics](https://sliksvn.com/support/subversion-basics-using-check-out-update-check-in-commit/)

4. [Subversion book](http://svnbook.red-bean.com/)

## Globally search for a regular expression and print matching lines (grep)

[grep](https://en.wikipedia.org/wiki/Grep) is a command line utility for searching plain text data sets for lines that match a regular expression. Refer the [grep manual](https://www.gnu.org/software/grep/manual/grep.html) for more commands.

## Git

[Git](https://en.wikipedia.org/wiki/Git) is also a version control system for tracking changes in any files and directories. View [git documentation](https://git-scm.com/doc) for learning git commands.

## GitHub

Some resources that are useful while using GitHub are:

1. [Creating a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)

2. [Opening an issue from code](https://docs.github.com/en/github/managing-your-work-on-github/opening-an-issue-from-code)

3. [Resolving a merge conflict on GitHub](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github)
